### ISSUE TITLE
Scertain genuses missing in tbl_taxa_tree_genera.genus_name

### ISSUE THREAD

**Issue by MGE4** [humlab-sead/sead_clearinghouse_import#12]
<img width="1136" alt="tbl_taxa_tree_genera genus_name-missing data" src="https://user-images.githubusercontent.com/49444339/68593113-06445080-0495-11ea-8e9c-143b397f0896.png">
tbl_taxa_tree_genera.genus_name like "Betula sp.", "Picea sp.", and "Alnus sp." etc. can not be found in SEAD_master_9.

**Comment by visead** [comment]
I think we went through this but will describe to make it clear.
tbl_taxa_tree_genera.genus_name should always be only genus name. Every genus should have 'sp.' and preferably 'spp.' entry as tbl_taxa_tree_master.species. These entries may need creating to cater for new data as they were not created when MAL data were entered.
