### ISSUE TITLE
Abundances missing for dendrochronology

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_clearinghouse_import#13]
In theory, any dendrochronological sample where wood species have been identified should have an abundance value for the taxon. This does not appear to be the case when testing Supersead... needs investigating from data import level.

**Comment by MattiasSealander** [comment]
This is currently stored in tbl_dendro, as metadata surrounding the dating (stored in dendro_dates). Species is on a genus level (tall, gran, ek, bok), these can be identified easily in tbl_dendro, where accompanying analysis_entity_id is also stored. Should be possible to update tbl_abundance with this.

**Comment by roger-mahler** [comment]
Fixed in Excel data.
